#!/bin/python

import math
import os
import random
import re
import sys


# Complete the tasks function below.
parent = []
def find(x):
    if parent[x] == x:
        return x
    parent[x] = find(parent[x])
    return parent[x]
def union(x, y):
    px = find(x) 
    py = find(y)
    if(px == py):
        return False
    parent[px] = py
    return True
     
def tasks(n, a, b):
    global parent
    parent = [x for x in range(n+1)]
    c=0
    for x,y in zip(a,b):
        if(not union(x,y)):
            c+=1

    return n  - c
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(raw_input().strip())

    a_count = int(raw_input().strip())

    a = []

    for _ in xrange(a_count):
        a_item = int(raw_input().strip())
        a.append(a_item)

    b_count = int(raw_input().strip())

    b = []

    for _ in xrange(b_count):
        b_item = int(raw_input().strip())
        b.append(b_item)

    res = tasks(n, a, b)

    fptr.write(str(res) + '\n')

    fptr.close()
